language: node_js
notifications:
  email: false
dist: xenial
node_js:
- 8
- 6
- 10
- node
before_deploy:
- git config --local user.name "$TRAVIS_AUTHOR_NAME"
- git config --local user.email "$TRAVIS_AUTHOR_EMAIL"
deploy:
  provider: script
  script: npx semantic-release
  skip_cleanup: true
  on:
    branch: master
    node: 8
    os: linux
sudo: false
env:
  global:
  - secure: SyCNOdW+Z3kQNPVwjoBBnHJ8ooD2O/QeKQXMdO8We6N31VfviJf2EgNXPC3FEhTNgLiaD37lT/jcYnZk0cAtZqS4Of77dCqR6GdNFnCECTYDUaIFYKI3/cNT0AhGvIUJLZytxVV4BpG213RC/lFb4GpiJsLhwovZYItnhnIlVmYVuw5Woqclpt1zUE/PfeFeQ79AMgGFhYU4WifKT6oW+ni/FJtJjOR/7sFFg4sWi7ntibPytXVPdQBupCWzFAtc9t+2shPwX1U2DaQFrISZ94scUfGgJXR3v2zNkawWE5hiJK2EPKQwfpO+dsrBvXTD1PBqF/tAO4E8xFAOb9ahOHLZzkcx0wd35tt7f/7TFGqh3xnr0Kl8CfTetqXM0SKPFYaLp8lSC4VNAR9nxVHiZphgDXrrQU5Mmy+SI6EH0gLBEU20DVbKMYeDdbxdCFYSdFRJ8+jJJDC94WSuROawLKvrRDL+RhkxjCdC8qMfds1btkQ1Zr/GrLTqm8LltHi9Q8hnn7DuTsxvChicP6hFJW/YlHBpRNnj0qbh6vS6RpRnhvbGOVYJPmMr+oZASNMOuRbRFY2uzOInHfkp84og19898DSE69+hO6nd/7e8QBb75Mob0GkXZEfPDkQdAT4l+yForrZFChSPClNJB3dEfDgGrXVEAk2SGyKjO2TFoBA=
  - secure: cBOnfRvIL5pzS+iPEFw3soYHTD6dEFOHpRxGJQnOGOZKEpyMsptip+FVoyidPzePLUHon88qLbn9bZRcDjRj4ZelhUaRbJAX0UbUOezP4zUXAgc6rVMetcc7KEiDaORE+posSQqomJoFiZ8oa4L/YfaxlkKh2QU2+ZQKP4LacOr6/9zjh+5d1pxCvazBbJPSxOg2X08nVSPa8Xm7J0FDV4TI9It5XLdf+UidhCZ0IUAvptNN/BBNyHcgBKjn6f20HGPiagLaF/NbbQnkZAo6K0n8B/7V+5VoiT6Mul88J4fsiSJCfhDGN3Azf8nmiUKHbuciPVHyIjYvLbLLmog4Co1gJTd7rzqk3xgyFE2+pIfmDqMI01LZihKVGXw3ZFaSFDYOkrxLVIkGgNXwOGfOUzejVUkKB/l1D040OzPiV2PKTQSrflVP1uyROy6dk7hXKi+A7YtDOc3nDToR9+sY6PDeFwjH5HE5FIxZsRlyftgh1GsRFhFjRbSg20prp1IInkTB6YQBlYiOsg/pwkS6XNMq2EbrHPw3tRdefgTHRULmoq1VuqSrrvgyaIcoCGhYFVEdfSs+ppudLAQ7zq07aSlY775JhbvMFn2FzhY0RqvsFqqtoVlFDKvtMbRitt2FER76VAchKgCLJ/A2ZGzCIGv5/5Kt8cFBPhaf/sY9CcI=
  - secure: Gh9hqiX9aUSGtfefAouWdJyNW3KjJikY51YYEIJrqJsb0ZkFWl29Gq/X1EPn5QdT8iTamz2DapA7gWtuc1In+fvQhoi0Vc6E2YwlwjTOB3o4v96E4Cbjj/NhD6y61kw/y5dU4ED3Oi03nnezR4FZrxXcMRjfvNj0P9ZYRE7v9mVYFguthPuHcIS+jkaCtQ6dA7IabIqUj/za9uxkhzg+3lDVG/G+rKZd9sWB02DwEDLzawnFOt8VcGOn6J4vMRDL0S3Ga+5ezkAphf+TeGbA5IAMy2GBjZ0Pg0X57CXHX4qGs9Vv1C64L8jpca8JHGJ7xO3cGLp2vw1fgR8N7WHtqCB+3Bm1Gh7gqidQ/OlvRgHIM3OhyuNhzZ/2cvmyH9ZSwzyhOT3m9FmZMD/N48o4y8pke7ett4PezsTKXfl+2CHySQ3NwG0qr/N7yneHgeSsnRGPRobBxehAwgp4wj5b92e/xgveUv9hmEqBdDign2sE2XznZ64KqXGhB6wq14sd1xPAKgkBkXlZLqzSeuMNKVqFysq8pYlITFe3n3KpUTQbL/xLC2LE9ugoXgI4Bbb0BthcrrKZiC+LNIzNZ2+N5U/e8lUDOzfCHuLEST8vhh3ECGaBla9E43SjA7IeMcZidZp1t2swcq5Fkms+wj91JVZG3IRiwXLT41mcZd62ubA=
