language: java
notifications:
  email: false
os: linux
dist: bionic
jdk:
  - oraclejdk11
before_install:
  - nvm install 10
install: ./gradlew assemble
after_install:
  - npm install -g npm
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    > ./cc-test-reporter && chmod +x ./cc-test-reporter && ./cc-test-reporter before-build
script: ./gradlew test
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT;"
before_deploy:
  - git config --local user.name "$TRAVIS_AUTHOR_NAME"
  - git config --local user.email "$TRAVIS_AUTHOR_EMAIL"
deploy:
  provider: script
  script: npx semantic-release
  skip_cleanup: true
  on:
    branch: master
sudo: false
env:
  global:
    - secure: uHnnN0FMgf8NRy5smoRt351fXngIHwESYggseOcPso21s/mIkc24wPIvEp/YxQpU+2WH08P1yJo0m+953EOScD/YY61e/owqfSvMvz6n4B1tCxwB4wPy+JFx6Wc9NzNEKghbLyZH40Xz2lLu5bKLfTgYYEVsdIlk1eedIfdfFjf3bIlAvppVrDUQqLV2U1B7q3Db+kAd3aal5BmwxsjLlBL/M4n0rd+Lud/VOVM02QPTHhE2DlsIWL49prBo7TGLmr2Vm7hWn9CK5AdyIWrBEbbSjUtm1fPnqAu2TyfsNhFfRRVtN4s9dA8U5Q54Ib2CHkuPkaRv3oCSR+DgELNtlEDgoWqy6Kfnju5Pv68qyIsStqU4wljA34iMg13nB1EMA+QOKsnZC4HTqY9Ufh7rSU/Dqlrh+5O9LNq/M6oBCXCmBFSAgjg7sgTjguSvtBoEqad96gyWaCEYyRO3ee7BbdRSd8+VJ1N7f3zx6CN3vEb2LeoplY1YiNGl6PCjicjxpDV1bFcEP3Vwbrtkukh3jaUicXxL5MrxmqfDRRgswP+ZwXYxIN4Yo4iEirsbw/PQ8KvIdYNFi34A0C+1Su3zmcB9GwZLkMgMT3qJbkfEz4DCsIivYcZ4537hM2rqV3CO4cHUC0XLnwjbcrsgxuiW0Ydlqs3NgEh2ObTgcwJC4DQ=
    - secure: xbaQXMpd+F58WHkquDAUsC9vDlEP2FZbVch5XH/Ub6uGFUik5b/3m+uf0W3aFaFXruK4F0UbsGqNsRsVyFcFau/UFreCTbGWRa3yWOEZFNg1g4oD3eqT4IxU4l189GZEteZt0QU/m3SHWW/4ASXJTNMO4I7KAyHW65+KSY0DpUT6mFTHZOdrjdujAnDfabVCTpf7C7GjTuuAQ+Lez6sOBkahEzgpCCtGtO8r53H9gEUnV6x4IOq+PuRmFSUqJcMmE8UTzT4NFZ5Da2hcjqmRWkOo2m7aYbeASWjVPjFO0HpDbRrVaA4oHiQRNgHXyEAnRLOjEpLQ1JUfyD0jbl3O6ZyFhEu5+ilFapnkeWs5rg0R4kdKtP/zCNa0PTUF0Yw+SfSUsYR0M0pDv4Z65vPIikxd+o8YtRoXb2i/iveNrKAcsqIhWYACp8onoxZJFqpi2Qe/k0VA9CnqP8D5r96XgyZPbdilQmcwcR/IAVLWZfi0/gSHOY0wvgYDx8XifWtGKVxlT4WpIQE5x0RNAtUerxeDhYoBbH4lHkhEJnDp5r7mV9wpuwC8N6dMih2ReVXa/5lmp2+6nbCRhfteDQijW8f+4gzWztn0gi8U/Gk6ghO7bfvUGlAb+Qa22/BcHvUMUvfWuiInZSFSabD/1+8NHJnTTS2A0iuwA3ys1cAP1dM=
    - secure: WeWmzGHCGyrsWcBl9E8G7tQ7jcO4K+b+qa8HE7atrGTQnnHrE8vQFc2d/oDmqQRvBosXqbslgqnUDPPvCOF0t1ejBwagkYNtV9xTUJKTI0qANM3NECBDGdh0JDDdEGg+rv+ePmCrblnLQat6zuDFFnH9tpcLq66fPRo30IBQLxzn+iCD5Kdrz8rhqgrpW1aNo3X1458JC3KlqkhnI3A+scvslwNXeSnQzULIh3dcBRLn8BtMdFZYSsRawCDLIoxmQXZo4YzIKFG3zboAPnvTXfl9uDUfIRIH5F23EdSOCYrjjK1aL7WUSgJxGx8zIZRVkS5omPq4VLDqgGucmbD8WzjADPYaJF4+JEgypt8+Y/4C6AiFh5SvVC3rdjUFIU2XRoQmW0MGiANyosKkd9cM7/CKAze2qnf+2JDLxcry+CjvmA4eVwrPG4TIBciHHQy8Uh6IMrFSWxYlFEdRnDgliKhFbAwuOFOlkxcIGdnFByzk4LLuewNKpHDIQRy4BNTMql1HFFTQZtg/KuOUBNj+33NpvnsqtXPAA0K18q2q+vppalzeQNKY69BtyvfyeKiKld24RDI2ZOdSxtdOrJhoN8t9Frki7sHXuSorZE89qxTxm0bc3wxCKDa3F8lIxBX6nADZhMjQ4wRjyeku6Xuj8evfQHxdyVzXuMGrZXqs35E=
    - secure: Q4zbsLpmNUs6Yp79Y508ZzfQ0zRznJKuTjHyT7iHrB02i5EbVhpgZMu1G/Yw5rFeifFbMnTrvsqctaqyBLvHSdPdPHA89C9g/Qg7Swl7Zix7GkHugBJH6R61LSmLimH/9JzqLEZp12b7t4otCCZmV20de/gZMjO1rf1+lBFqSkcXh5mrMKXATVkRePrC8bSB/WrLJxPqZ711UpMZVYEDwRv18/zuZdYTO8K+W6xnYEJWHGpCqKpgC911Tj7+h4T+yUO9MF8okB2UN9unuL6Hn/kp/XFIo/xViTZR9wH8JcqIjue9glbOuZubL7NrczapWLwIXRwNbmBk2ur8l5RAkCu11Sx3NALwU0zF9bCe0Oyj8IIBZ/Jxl+yaIL7lvmiTOtjm4ZizTtV62Na/pos6GhFisdsgTSEM235uXR5gMlMxpdJekpPAI3Kab7z1SsAtihbceD4A02+cl5sVYfABr2VHhc7TNgs4nPnOjX3LuQAYW+vjsn4Ol5MtUlDRkpw9B8fI9hpiygwKvBu1lrBBc01PIdkHomSGOpyq3x2y8CSsXj6F9rfSM39Fe30jfDvUOUlYxUuvPU4a7Zw/4N78Po678ErVyKv0huQnEA13uGjyj0d3ftfu+oebL/IscC1Hfyn1dXWo7OFLvka9k1sLVYaW6D2eG6cAHvUIs9CO4EU=
